# Generated by Django 2.1.2 on 2018-12-28 17:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('economic', models.IntegerField(default=50)),
                ('social', models.IntegerField(default=50)),
                ('environmental', models.IntegerField(default=100)),
            ],
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Building', max_length=40, unique=True)),
                ('version', models.CharField(default='jelly', max_length=20)),
                ('description', models.TextField(default='A rather plain building.')),
                ('money', models.IntegerField(default=0)),
                ('hydrocarbons', models.IntegerField(default=0)),
                ('food', models.IntegerField(default=0)),
                ('electricity', models.IntegerField(default=0)),
                ('pollution', models.IntegerField(default=0)),
                ('waste', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Ragnarok', max_length=40, unique=True)),
                ('version', models.CharField(default='jelly', max_length=20)),
                ('description', models.TextField(default='Today will be a sunny day.')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='A random game', max_length=20)),
                ('current_index_pile', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='GameEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='game.Game')),
            ],
        ),
        migrations.CreateModel(
            name='HydrocarbonSupplyPile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_amount', models.FloatField(default=0)),
                ('multiplier', models.IntegerField(default=0)),
                ('index', models.IntegerField(editable=False)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hydrocarbon_piles', to='game.Game')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='game.Game')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerBuilding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(editable=False)),
                ('unlocked', models.BooleanField(default=False)),
                ('number_of', models.IntegerField(default=0)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buildings', to='game.Player')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerTechnology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(unique=True)),
                ('unlockable', models.BooleanField(default=False)),
                ('unlocked', models.BooleanField(default=False)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technologies', to='game.Player')),
            ],
        ),
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.IntegerField(default=0)),
                ('hydrocarbon', models.IntegerField(default=1)),
                ('food', models.IntegerField(default=0)),
                ('electricity', models.IntegerField(default=0)),
                ('pollution', models.IntegerField(default=1)),
                ('waste', models.IntegerField(default=0)),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='game.Player')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Resources',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.IntegerField(default=10)),
                ('hydrocarbon', models.IntegerField(default=0)),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='game.Player')),
            ],
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='game.Profile'),
        ),
        migrations.AddField(
            model_name='building',
            name='technology',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.Technology'),
        ),
        migrations.AddField(
            model_name='balance',
            name='player',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='game.Player'),
        ),
    ]
