# Generated by Django 2.1.2 on 2018-11-25 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HydrocarbonSupplyPile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_amount', models.IntegerField(default=0)),
                ('multiplier', models.IntegerField(default=0)),
                ('index', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('technologies', models.IntegerField(default=0)),
                ('builded', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('um', models.IntegerField(default=0)),
                ('hydrocarbons', models.IntegerField(default=0)),
                ('food', models.IntegerField(default=0)),
                ('electricity', models.IntegerField(default=0)),
                ('pollution', models.IntegerField(default=0)),
                ('waste', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Resources',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('um', models.IntegerField(default=0)),
                ('hydrocarbons', models.IntegerField(default=0)),
                ('pollution', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='States',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('economical', models.IntegerField(default=50)),
                ('social', models.IntegerField(default=50)),
                ('environmental', models.IntegerField(default=100)),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='production',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='game.Production'),
        ),
        migrations.AddField(
            model_name='player',
            name='resources',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='game.Resources'),
        ),
        migrations.AddField(
            model_name='player',
            name='states',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='game.States'),
        ),
    ]
