# Generated by Django 2.1.2 on 2018-12-09 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hydrocarbonsupplypile',
            name='index',
            field=models.IntegerField(editable=False),
        ),
    ]
