# Generated by Django 2.1.2 on 2018-12-02 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hydrocarbonsupplypile',
            name='stock_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(default="Anne O'NYME", max_length=100),
        ),
    ]
