# Generated by Django 2.0 on 2018-12-03 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resources',
            name='pollution',
        ),
    ]
