# Generated by Django 2.1.2 on 2018-12-22 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20181211_1919'),
    ]

    operations = [
        migrations.RenameField(
            model_name='production',
            old_name='hydrocarbons',
            new_name='hydrocarbon',
        ),
        migrations.RenameField(
            model_name='resources',
            old_name='hydrocarbons',
            new_name='hydrocarbon',
        ),
        migrations.AlterField(
            model_name='game',
            name='name',
            field=models.CharField(default='A random game', max_length=20),
        ),
    ]
