# Generated by Django 2.0 on 2018-12-13 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20181211_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='name',
            field=models.CharField(default='A random game', max_length=20),
        ),
    ]
