# Generated by Django 2.1.2 on 2018-12-22 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20181222_1302'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='States',
            new_name='Balance',
        ),
    ]
