# Generated by Django 2.1.2 on 2018-12-22 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_auto_20181222_1310'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TechnologyPlayer',
            new_name='PlayerTechnology',
        ),
        migrations.RenameField(
            model_name='balance',
            old_name='economical',
            new_name='economic',
        ),
    ]
