# Generated by Django 2.1.2 on 2018-12-22 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_auto_20181222_1319'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BuildingPlayer',
            new_name='PlayerBuilding',
        ),
    ]
