# Generated by Django 2.1.2 on 2018-12-25 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_auto_20181222_1321'),
        ('game', '0004_auto_20181214_2128'),
    ]

    operations = [
    ]
