# Generated by Django 2.1.2 on 2019-01-14 12:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('economic', models.IntegerField(default=50)),
                ('social', models.IntegerField(default=50)),
                ('environmental', models.IntegerField(default=100)),
            ],
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(editable=False)),
                ('unlocked', models.BooleanField(default=False)),
                ('copies', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='A random game', max_length=20)),
                ('version', models.CharField(default='jelly', max_length=20)),
                ('era', models.IntegerField(default=1)),
                ('current_index_pile', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='HydrocarbonSupplyPile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_amount', models.FloatField(default=0)),
                ('multiplier', models.IntegerField(default=0)),
                ('index', models.IntegerField(editable=False)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hydrocarbon_piles', to='backend.Game')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='backend.Game')),
            ],
        ),
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.IntegerField(default=0)),
                ('hydrocarbon', models.IntegerField(default=1)),
                ('food', models.IntegerField(default=0)),
                ('electricity', models.IntegerField(default=0)),
                ('pollution', models.IntegerField(default=1)),
                ('waste', models.IntegerField(default=0)),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='backend.Player')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Resources',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.IntegerField(default=10)),
                ('hydrocarbon', models.IntegerField(default=0)),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='backend.Player')),
            ],
        ),
        migrations.CreateModel(
            name='SourceBuilding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Old mansion', max_length=40, unique=True)),
                ('slug', models.CharField(default='old-mansion', max_length=40, unique=True)),
                ('version', models.CharField(default='jelly', max_length=20)),
                ('era', models.IntegerField(default=1)),
                ('description', models.TextField(default='A rather plain building.')),
                ('cost', models.IntegerField(default=1)),
                ('money_modifier', models.IntegerField(default=0)),
                ('hydrocarbon_modifier', models.IntegerField(default=0)),
                ('food_modifier', models.IntegerField(default=0)),
                ('electricity_modifier', models.IntegerField(default=0)),
                ('pollution_modifier', models.IntegerField(default=0)),
                ('waste_modifier', models.IntegerField(default=0)),
                ('economic_modifier', models.IntegerField(default=0)),
                ('social_modifier', models.IntegerField(default=0)),
                ('environmental_modifier', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SourceEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Sunny day', max_length=40, unique=True)),
                ('slug', models.CharField(default='sunny-day', max_length=40, unique=True)),
                ('version', models.CharField(default='jelly', max_length=20)),
                ('era', models.IntegerField(default=1)),
                ('description', models.TextField(default='There is nothing to report.')),
            ],
        ),
        migrations.CreateModel(
            name='SourceTechnology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Fire discovery', max_length=40, unique=True)),
                ('slug', models.CharField(default='fire-discovery', max_length=40, unique=True)),
                ('version', models.CharField(default='jelly', max_length=20)),
                ('era', models.IntegerField(default=1)),
                ('description', models.TextField(default='Food may now be cooked.')),
                ('cost', models.IntegerField(default=1)),
                ('money_modifier', models.IntegerField(default=0)),
                ('hydrocarbon_modifier', models.IntegerField(default=0)),
                ('food_modifier', models.IntegerField(default=0)),
                ('electricity_modifier', models.IntegerField(default=0)),
                ('pollution_modifier', models.IntegerField(default=0)),
                ('waste_modifier', models.IntegerField(default=0)),
                ('economic_modifier', models.IntegerField(default=0)),
                ('social_modifier', models.IntegerField(default=0)),
                ('environmental_modifier', models.IntegerField(default=0)),
                ('parent_technology', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_technology', to='backend.SourceTechnology')),
            ],
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(unique=True)),
                ('unlocked', models.BooleanField(default=False)),
                ('purchased', models.BooleanField(default=False)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technologies', to='backend.Player')),
            ],
        ),
        migrations.AddField(
            model_name='sourcebuilding',
            name='parent_technology',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_building', to='backend.SourceTechnology'),
        ),
        migrations.AddField(
            model_name='player',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='backend.Profile'),
        ),
        migrations.AddField(
            model_name='game',
            name='source_buildings',
            field=models.ManyToManyField(to='backend.SourceBuilding'),
        ),
        migrations.AddField(
            model_name='event',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='backend.Game'),
        ),
        migrations.AddField(
            model_name='building',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buildings', to='backend.Player'),
        ),
        migrations.AddField(
            model_name='balance',
            name='player',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='backend.Player'),
        ),
    ]
